name: iKCHECK
# name: ikcheck
description: A new Flutter project.

publish_to: "none"

version: 2.1.9+22

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  badges: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^0.22.0
  google_fonts: ^2.3.1
  restart_app: ^1.1.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0
  url_launcher: ^6.1.5
  flutter_secure_storage: ^5.0.2
  encrypt: ^5.0.1
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_html: ^3.0.0-alpha.3
  video_player: ^2.0.2
  visibility_detector: ^0.3.3
  flick_video_player: ^0.3.1
  flutter_math_fork: ^0.3.3
  easy_localization: ^3.0.1
  firebase_messaging: ^11.2.6
  firebase_core: ^1.10.0
  flutter_local_notifications: ^9.2.0
  carousel_slider: ^4.1.1
  photo_view: ^0.13.0
  dbcrypt: ^2.0.0
  webview_flutter: ^3.0.4
  firebase_dynamic_links: ^4.2.5
  share_plus: ^4.0.4
  loading_animation_widget: ^1.2.0+1
  package_info_plus: ^1.4.2
  launch_review: ^3.0.1
  flutter_session_manager: ^1.0.2
  chewie:
  dots_indicator: ^2.1.0
  persistent_bottom_nav_bar: ^4.0.2
  get: ^4.6.5
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/ikCheckLogo 2.png"
  image_path_android: "assets/images/ikCheckLogo 2.png"
  # android: "launcher_icon"
  # ios: "launcher_icon"
  # image_path: "assets/images/ikCheckLogo 2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - assets/i18n/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: IkCheckKey
      fonts:
        - asset: assets/icons/IkCheckKey.ttf
